//
// NewsList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct NewsList: Codable {

    public var status: String?
    public var totalResults: Int?
    public var articles: [Articles]?

    public init(status: String?, totalResults: Int?, articles: [Articles]?) {
        self.status = status
        self.totalResults = totalResults
        self.articles = articles
    }

}
